### ISSUE TITLE
Incorrect information in transaction monitoring page

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#723]
### Actual behavior

For Register delegate, i see 11 items in the table but in the graph i'm seeing only 9 items. Same for delegate misbehaviour and register multi signature group, the data conflict between the graph and table

### Expected behavior
Number of transaction in the graph and list should be same

### Which version(s) does this affect? (Environment, OS, etc...)
V0.4.4
![image.png](https://images.zenhubusercontent.com/5cf53f0cd8501ed6b9d4ccce/8f657836-010f-4cb6-b992-ad25b8de0433)

**Comment by MichalTuleja** [comment]
We need to make sure that:

- intervals are configurable by environment variables
- statistics generation procedure scales well for a larger traffic

Based on that input we can decrease intervals on the production servers.

**Comment by ManuGowda** [comment]
@sameersubudhi cross check if the issues exits.

**Comment by sameersubudhi** [comment]
The current day stats seem to be incorrect (perhaps an edge-case scenario) and needs more proper investigation.

**Comment by nagdahimanshu** [comment]
After doing more investigation, we found out that issue mentioned above is not a valid issue. The reason is, the graph shows transactions only for the last one week, 6 months or 1 year but the table shows all-time transactions. 

One more issue pointed is current day stats seem to be incorrect. It happens only for new transactions but the current transaction statistics implementation already takes care and update current day stats every 30 mins.

**Comment by sameersubudhi** [comment]
The transaction stats calculations seem to be correct from Lisk Service (all based on GMT). However, the confusion was due to the fact that on Lisk Desktop, the transaction timestamps (under the `Date` property) are displayed based on the current user locale.

Since the observation was made in Berlin (CET, viz. GMT +1:00), the transactions from 2300 hrs GMT (previous day) are displayed as the current day's transaction in CET. Perhaps, it would be better if Lisk Desktop showed the GMT date alongside the transactions or add a tooltip to highlight the fact that the transaction stats are calculated based on GMT timings but the transaction timestamps are displayed in the current locale.

**Comment by MichalTuleja** [comment]
Closing the issue based on the provided feedback.
